### PR TITLE
change loading time of model and modelz to save some Gpu space

### PR DESCRIPTION
**Pull request by OmarSayedMostafa**
swap between model and modelZ help who have GPU memory less than or equal 2 GB to save some space and prevent the code from crash because of leak of memory.

### CODE REVIEW

**Comment by 1adrianb** [comment]
Hi @OmarSayedMostafa ,
Thanks a lot for your contribution!
The code looks good, however since this will slowdown the process by quite a bit (having to reload the models from the disk at each step), could you please keep both approaches and enable the new one via a flag, so users can select this behaviour only if they indeed have a memory issue?

Thanks,
Adrian

**Review by 1adrianb — CHANGES_REQUESTED** [review]
Hi @OmarSayedMostafa ,
Thanks a lot for your contribution!
The code looks good, however since this will slowdown the process by quite a bit (having to reload the models from the disk at each step), could you please keep both approaches and enable the new one via a flag, so users can select this behaviour only if they indeed have a memory issue?

Thanks,
Adrian

**Comment by OmarSayedMostafa** [comment]
hi @1adrianb,
I edited the code to provide the limited Gpu memory option "-limitedGpuMemory", i tried to improve the way of reloading by make the code load the model to Cpu memory once and clone it when needed from the Cpu memory to Gpu memory (as i think it will be a little faster).

regards,
Omar

**Review by 1adrianb — APPROVED** [review]

**Comment by 1adrianb** [comment]
Great, thanks a lot @OmarSayedMostafa !

**Pull request merged**
